<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="LAPTOP-5KMFOFH9" failures="1" tests="1" name="Default test(failed)" time="0.088" errors="0" timestamp="2024-06-15T13:07:59 IST">
  <testcase classname="testNgDemo.TestDemo_EnableArgument" name="logoutTest" time="0.024">
    <failure type="java.lang.AssertionError" message="expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at testNgDemo.TestDemo_EnableArgument.logoutTest(TestDemo_EnableArgument.java:35)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- logoutTest -->
  <testcase classname="testNgDemo.TestDemo_EnableArgument" name="addToCartTest" time="0.0">
    <ignored/>
  </testcase> <!-- addToCartTest -->
  <testcase classname="testNgDemo.TestDemo_EnableArgument" name="searchTest" time="0.0">
    <ignored/>
  </testcase> <!-- searchTest -->
  <testcase classname="testNgDemo.TestDemo_EnableArgument" name="registerTest" time="0.0">
    <ignored/>
  </testcase> <!-- registerTest -->
  <testcase classname="testNgDemo.TestDemo_EnableArgument" name="loginTest" time="0.0">
    <ignored/>
  </testcase> <!-- loginTest -->
</testsuite> <!-- Default test(failed) -->
